// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxk1kylJnmgXexgYEBm16YElOZvvDFXo',
    appId: '1:1089598126282:web:5f5a8851a403136a7a5c33',
    messagingSenderId: '1089598126282',
    projectId: 'hbosfirestoredb',
    authDomain: 'hbosfirestoredb.firebaseapp.com',
    databaseURL: 'https://hbosfirestoredb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hbosfirestoredb.appspot.com',
    measurementId: 'G-4HTCKVHR0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1yE46-f8yuO1yoBOl1UnfTph9361PpkU',
    appId: '1:1089598126282:android:7c12558cb33f6e8a7a5c33',
    messagingSenderId: '1089598126282',
    projectId: 'hbosfirestoredb',
    databaseURL: 'https://hbosfirestoredb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hbosfirestoredb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oyUIAxAiIM4G8FKVwB7Jfovs_wTKBYE',
    appId: '1:1089598126282:ios:a0aa908f91b1d2267a5c33',
    messagingSenderId: '1089598126282',
    projectId: 'hbosfirestoredb',
    databaseURL: 'https://hbosfirestoredb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hbosfirestoredb.appspot.com',
    iosBundleId: 'com.projects.hbosFirestoreDB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6oyUIAxAiIM4G8FKVwB7Jfovs_wTKBYE',
    appId: '1:1089598126282:ios:a0aa908f91b1d2267a5c33',
    messagingSenderId: '1089598126282',
    projectId: 'hbosfirestoredb',
    databaseURL: 'https://hbosfirestoredb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hbosfirestoredb.appspot.com',
    iosBundleId: 'com.projects.hbosFirestoreDB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxk1kylJnmgXexgYEBm16YElOZvvDFXo',
    appId: '1:1089598126282:web:4eb7b71f799e16ab7a5c33',
    messagingSenderId: '1089598126282',
    projectId: 'hbosfirestoredb',
    authDomain: 'hbosfirestoredb.firebaseapp.com',
    databaseURL: 'https://hbosfirestoredb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hbosfirestoredb.appspot.com',
    measurementId: 'G-Y8MJ9W9MRR',
  );
}
